// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { DownloadProvider } from "@/app/asr/features/components/DownloadContext";
import Notification from '@/app/components/ui/Notification'
import RecordingStatusIndicator from "@/app/components/ui/RecordingStatusIndicator";
import MagicCircle from "./ui/MagicCircle";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Arielle",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-white min-h-screen">
                <DownloadProvider>
                    <MagicCircle />
                    <RecordingStatusIndicator />
                    {children}
                    <Notification />
                </DownloadProvider>
            </body>
        </html>
    );
}
